name: 01 - Building Blocks # Workflow name
on: # Trigger the workflow on push or on a schedule
    push:
    workflow_dispatch:

jobs: # Define the jobs to run in the workflow
    echo-hello: # Job name
        runs-on: ubuntu-latest # The type of runner to run the job on
        steps: # Steps to execute in the job
            - name: Say Hello
              run: echo "Hello, World!"
    echo-goodbye: # Job name
        runs-on: ubuntu-latest # The type of runner to run the job on
        steps: # Steps to execute in the job
            - name: Successful Step
              run: |
                  echo "I will Succeed"
                  exit 0
            - name: Say Goodbye
              run: echo "Goodbye!"
