name: 03 - Workflow Runners # Workflow name
on:
    workflow_dispatch:

jobs:
    ubuntu-runner:
        runs-on: ubuntu-latest
        steps:
            - name: Show OS
              run: |
                  echo "this job in running on a ubuntu runner"
                  echo "Runner OS: $RUNNER_OS"
                  echo "OS INFO: ${{ runner.os }}"

    windows-runner:
        runs-on: windows-latest
        steps:
            - name: Show OS
              shell: bash
              run: |
                  echo "this job in running on a windows runner"
                  echo "Runner OS: $RUNNER_OS"
                  echo "OS INFO: ${{ runner.os }}"

    macos-runner:
        runs-on: macos-latest
        steps:
            - name: Show OS
              run: |
                  echo "this job in running on a macOS runner"
                  echo "Runner OS: $RUNNER_OS"
                  echo "OS INFO: ${{ runner.os }}"
