name: 17 - 2 - Custom Action - JS
run-name: 17 - 2 - Custom Action - JS | BB - ${{ inputs.base_branch }} TT - ${{ inputs.target_branch }} WD - ${{ inputs.working_directory }}

on:
    workflow_dispatch:
        inputs:
            base_branch:
                description: 'The branch used as the base for the dependency update checks'
                required: false
                default: 'main'
            target_branch:
                description: 'The branch from which the PR is created'
                required: false
                default: 'dependency-update'
            working_directory:
                description: 'The working directory of the project to check for dependency updates'
                default: '17-custom-actions/react-app'
                required: true
            debug:
                description: 'Whether the output debug messages to the console'
                default: 'false'
                required: false

permissions:
    contents: write
    pull-requests: write

jobs:
    dependency-update:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6
            - name: Check of dependency updates
              id: update-deps
              uses: ./.github/actions/js-dependency-update
              with:
                  base_branch: ${{ inputs.base_branch }}
                  target_branch: ${{ inputs.target_branch }}
                  working_directory: ${{ inputs.working_directory }}
                  gh_token: ${{ secrets.GITHUB_TOKEN }}
                  debug: ${{ inputs.debug }}
            - name: Print Custom Action Output
              run: |
                echo "Update Available: ${{ steps.update-deps.outputs.update_available }}"
